[package]
name = "actix-web-validator"
version = "1.0.1-alpha.0"
authors = ["Kolomatskiy Artem <kolomatskiy@bk.ru>"]
edition = "2018"
description = "Validation mechanism for actix-web"
keywords = ["actix-web", "serialization", "querystring", "validator", "validation"]
categories = ["encoding", "web-programming"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rambler-digital-solutions/actix-web-validator"
documentation = "https://docs.rs/actix-web-validator/"

[dependencies]
actix-web = "3.0.0-beta.1"
derive_more = "0.99"
actix-http = "1"
validator = "0.10"
validator_derive = "0.10"
serde = "1"
serde_urlencoded = "0.6"
serde_json = "1.0.48"
log = "0.4"
futures = "0.3"
mime = "0.3"
bytes = "0.5"
actix-router = "0.2"
futures-util = "0.3.5"

[dev-dependencies]
actix-service = "1"
serde_derive = "1"
actix-rt = "1.1.1"
